// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	/*std::shared_ptr<CANTalon> lf;
	std::shared_ptr<CANTalon> rf;
	std::shared_ptr<CANTalon> lr;
	std::shared_ptr<CANTalon> rr;
	*/

/*
	std::shared_ptr<TalonSRX> lf;
	std::shared_ptr<TalonSRX> rf;
	std::shared_ptr<TalonSRX> lr;
	std::shared_ptr<TalonSRX> rr;
*/


	std::shared_ptr<RobotDrive> mecanum;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<NetworkTable> table;


public:
	std::shared_ptr<CANTalon> lf;
		std::shared_ptr<CANTalon> rf;
		std::shared_ptr<CANTalon> lr;
		std::shared_ptr<CANTalon> rr;
	DriveTrain();
	void InitDefaultCommand();


	float driveToAngle(double targetAngle);
	double angleToTurn(double currentAngle, double targetAngle);
	double calculatePID(double setpoint, double current, double Kp, double Ki, double Kd);

	//New Stuff

	float ReturnEncoderDistance();
	void ResetEncoderDistance();
	float ReturnGyroAngle(float gyroPosition);
	void ResetGyroAngle();


	//Working Stuff
	void takeJoystickInputs(double x, double y, double z, double angle);
	void autoDrive(double x, double y, double z, double angle);
		void stop();
	double Db(double axisVal);
	void takeAutoInputs(double y1, double y2);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
