// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTONOMOUS_COMMAND_H
#define AUTONOMOUS_COMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutonomousCommand: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutonomousCommand();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	void setAutonStep(int autonStep);
	int getAutonStep();

	void setElapsedTime(double elapsedTime);
	double getElapsedTime();

	void setStartTime(double startTime);
	double getStartTime();

	void setUsedEncDist(float totalDist);
	float getUsedEncDist();

	void setUsedStrafeRightEncDist(float strafeRightDist);
	float getStrafeRightEncDist();


	void auton1();
	void auton2();
	void auton3();
	void auton4();
	void auton5();
	void auton6();
	void auton7(); //shooter position #3


private:
	int autonStep = 1;
	float usedEncDist = 0.0;
	float strafeRightDist = 0.0;
	double startTime = 0.0;
	double elapsedTime = 0.0;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
