// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <Commands/Autonomous/Shooting/AutoTurnToShoot.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoTurnToShoot::AutoTurnToShoot(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoTurnToShoot::Initialize() {
	NoTurnIt();
}

// Called repeatedly when this Command is scheduled to run
void AutoTurnToShoot::Execute() {
	TurnIt();
}

// Make this return true when this Command no longer needs to run execute()
bool AutoTurnToShoot::IsFinished() {
	/* gyroang = drivegyro->GetAngle();
	 * if(gyroang > 36.00 degrees or whatever Andrew ) {
	 * return true }
	 * else{
	 * return false;
	 * }
	 */

	if(RobotMap::drivegyro->GetAngle() > 90.0){
		return true;
	}
	else{
		return false;
	}
}

// Called once after isFinished returns true
void AutoTurnToShoot::End() {
	NoTurnIt();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoTurnToShoot::Interrupted() {

}
void AutoTurnToShoot::TurnIt(){
	Robot::driveTrain->takeJoystickInputs(0.0, 0.0, 0.55, 0.0);
	//RobotMap::ballFeederBallFeederSpike->Set(Relay::Value::kForward*0.7);
}
void AutoTurnToShoot::NoTurnIt(){

	Robot::driveTrain->takeJoystickInputs(0.0, 0.0, 0.0, 0.0);
}
