// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "CANTalon.h"
#include <iostream>
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <CANTalon.h>
#include <AHRS.h>
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS



// ************  Motors for CAN bus ***********
	static std::shared_ptr<CANTalon> driveTrainLf;
	static std::shared_ptr<CANTalon> driveTrainRf;
	static std::shared_ptr<CANTalon> driveTrainLr;
	static std::shared_ptr<CANTalon> driveTrainRr;


// ********* Motors for PWM ***************
/*static std::shared_ptr<TalonSRX> driveTrainLf;
	static std::shared_ptr<TalonSRX> driveTrainRf;
	static std::shared_ptr<TalonSRX> driveTrainLr;
	static std::shared_ptr<TalonSRX> driveTrainRr;
*/


	static std::shared_ptr<RobotDrive> driveTrainMecanum;
	static std::shared_ptr<SpeedController> ballFeederBallFeederSpike;
	static std::shared_ptr<SpeedController> conveyerSpeedController1;
	static std::shared_ptr<SpeedController> gearMoverGearSparkMotor;
	static std::shared_ptr<Encoder> shooterShooterEncoder;
	static std::shared_ptr<CANTalon> shooterShooterMotor;
	static std::shared_ptr<CANTalon> climberClimberMotor;
	static std::shared_ptr<SpeedController> shooterAdjusterShooterAdjust;
	static std::shared_ptr<AnalogInput> shooterAdjusterShooterPot;
	static std::shared_ptr<Relay> ledsLedSpike;
	static std::shared_ptr<Relay> ropeGatherRopeGatherRelay;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<AnalogInput> gearSideUltra;
	static std::shared_ptr<AnalogInput> nonGearSideUltra;
	static std::shared_ptr<SpeedController> ballSubFeeder;
	static std::shared_ptr<SpeedController> ballVibrator;


	//static std::shared_ptr<AHRS> driveGyro;
	static std::shared_ptr<AHRS> drivegyro;

	static std::shared_ptr<NetworkTable> steven;


	static void init();
};

#endif
